# Generated by Django 3.2.7 on 2022-03-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='user_image_default.jpg', upload_to='user_profile_image'),
        ),
    ]
