# Generated by Django 3.2.7 on 2022-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='content_image',
            field=models.ImageField(default='image_default.jpg', upload_to='article_img'),
        ),
    ]
