# Generated by Django 3.2.7 on 2022-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blogdetails_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='content_image',
            field=models.ImageField(blank=True, upload_to='article_img'),
        ),
    ]
